### ISSUE TITLE
HELP! :(

### ISSUE THREAD

**Issue by KrishaYue** [davecroman/TouchAndPlay#3]
System.NullReferenceException was unhandled

  Message=Object reference not set to an instance of an object.

 PlayerProfile profile = TAPDatabase.getProfile(profileComboBox3.SelectedItem.ToString());

**Comment by davecroman** [comment]
Hi KrishaYue,

Thanks for bringing up all these issues. It took a while for me to set the project again due to certain dependencies being deprecated. I believe I've fixed all the above issues in the recent commit. Please read the updated README.md file for instructions on how to run the app.

Let me know if all is well or if there are any other issues.

Cheers.

**Comment by davecroman** [comment]
Can I close this issue now?

**Comment by KrishaYue** [comment]
Yes Ofcour
