### ISSUE TITLE
sir patulong po 

### ISSUE THREAD

**Issue by Karla02** [davecroman/TouchAndPlay#4]
Hello po patulong po may error po kasi sya e ayaw ma build and yung installer pagkatapos ko iinstall ayaw mag run  ( I have kinect v1 SDK 1.5)

so eto po unang Warning 

**Could not find a part of the path 'C:\Users\Karla\AppData\Roaming\TouchAndPlay\profiles'.**
 string[] files = Directory.GetFiles(dirPath + profilesDir, "*.xml" );

so gumawa po ako ng Folder "TouchAndPlay" and "Profiles" sa 
AppData> Roaming > TouchAndPlay > Profiles

Tapos eto naman po yung next na Warning 

** NullReferenceException was unhandled**
**Object reference not set to an instance of an object.**

 PlayerProfile profile = TAPDatabase.getProfile(profileComboBox3.SelectedItem.ToString());

**Comment by davecroman** [comment]
Hi Karla,

Thanks for raising this issue. I will have a look at this issue tonight (Australia time) when I get home from work. i haven't touched this code in 5 years so it might take me a while to set this up. Cheers

**Comment by davecroman** [comment]
Hi Karla,

Thanks for bringing up all these issues. It took a while for me to set the project again due to certain dependencies being deprecated. I believe I've fixed all the above issues in the recent commit. Please read the updated README.md file for instructions on how to run the app.

Let me know if all is well or if there are any other issues.

Cheers.

**Comment by davecroman** [comment]
Hi Karla,

Let me know if you're happy for me to close this issue now. Cheers

**Comment by Karla02** [comment]
Maraming Salamat po sir
