### ISSUE TITLE
Method 2 Didnt work

### ISSUE THREAD

**Issue by StephenZach** [davecroman/TouchAndPlay#5]

**Comment by dunkelite** [comment]
Even the method 1 lol

**Comment by davecroman** [comment]
Hi Stephen,

Thanks for raising this issue. I will have a look at this issue tonight (Australia time) when I get home from work. i haven't touched this code in 5 years so it might take me a while to set this up. Cheers

**Comment by dunkelite** [comment]
Method 2 wont work because of this 
Could not find a part of the path 'C:\Users\YourComputer\AppData\Roaming\TouchAndPlay\profiles'.
string[] files = Directory.GetFiles(dirPath + profilesDir, "*.xml" );

I tried to create new but it didnt work

**Comment by KrishaYue** [comment]
Yup I agree with @dunkelite

**Comment by davecroman** [comment]
Hi everyone,

Thanks for bringing up all these issues. It took a while for me to set the project again due to certain dependencies being deprecated. I believe I've fixed all the above issues in the recent commit. Please read the updated README.md file for instructions on how to run the app.

Let me know if all is well or if there are any other issues.

Cheers.

**Comment by dunkelite** [comment]
WORKS LIKE A CHARM!!!! THANK YOU!

**Comment by davecroman** [comment]
Let me know if you guys are happy for me to close this issue now. Or you can close it yourself. Cheers.
